# -*- coding: utf-8 -*-
from . import ir_sequence
from . import account_invoice
from . import account_invoice_refund
from . import res_company
from . import res_partner
from . import res_country_state
from . import delivery_carrier
from . import stock_picking
from . import account_tax
from . import res_respresentants
from . import product_template
from . import dian_product_codes
from . import ir_cron
from . import sale_order
from . import res_users
from . import website
from . import website_page
from . import pos_session
from . import dian_edocs
from . import mail_template